#version: '3'
#
#services:
#  django:
#    build: .
#    container_name: django
#    command: /bin/bash -c "while ! nc -z pgdb 5432; do sleep 1; done && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - 8000:8000
#    depends_on:
#      - pgdb
#
#  pgdb:
#    image: postgres
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    container_name: pgdb
#    volumes:
#      - pgdbdata:/var/lib/postgresql/data/
#
#volumes:
#  pgdbdata: null

version: '3'

services:
  django:
    build: .
    container_name: django
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000

volumes:
  pgdbdata: null
